In [54]:
import pandas as pd
import numpy as np
from scipy import stats


import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [55]:
training_data = pd.read_csv("gmat_score.csv")

In [56]:
training_data

GMAT Score   WorkExp   InternationalAwards  Admission
0          750         0                    4        Yes
1          720         1                    2        Yes
2          710         2                    0         No
3          690         0                    1         No
4          670         4                    2        Yes
5          650         6                    2        Yes
6          600         1                    0         No

In [43]:
k = 3

In [57]:
query_data = pd.read_csv("query_point1.csv")
query_data                         

GMAT Score  Work Exp  International Awards
0         700         1                     2

In [64]:
query_data = np.array(query_data)
query_data

array([[700,   1,   2]], dtype=int64)

In [61]:
feature_data = np.array(training_data.iloc[: , :-1])
feature_data

array([[750,   0,   4],
       [720,   1,   2],
       [710,   2,   0],
       [690,   0,   1],
       [670,   4,   2],
       [650,   6,   2],
       [600,   1,   0]], dtype=int64)

In [62]:
target_data = np.array(training_data.iloc[: , -1:])
target_data

array([['Yes'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No']], dtype=object)

In [65]:
distances = np.sqrt(np.sum(np.square(query_data - feature_data),axis=1))
distances

array([ 50.04997502,  20.        ,  10.24695077,  10.09950494,
        30.14962686,  50.24937811, 100.019998  ])

In [66]:
def my_knn(training_data,query_data,k=3):
    
    
    query_data = np.array(query_data)
    feature_data = np.array(training_data.iloc[: , :-1])
    target_data = np.array(training_data.iloc[: , -1:])
    
   
    distances = np.sqrt(np.sum(np.square(query_data - feature_data),axis=1))
    sort_index = np.argsort(distances)
    top_k = sort_index[0:k]   
    nn_classes = target_data[top_k]
    pred = stats.mode(nn_classes)[0][0][0]
    
    return pred

In [67]:
my_knn(training_data,query_data,k=5)

'Yes'

In [68]:
my_knn(training_data,query_data,k=3)

'No'